Modules/Transisi/Routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('transisi')->group(function() {
        Route::get('company/export', 'CompanyController@export')->name('company.export');
        Route::get('employee/export', 'EmployeeController@export')->name('employee.export');
        Route::resource('company', CompanyController::class);
        Route::resource('employee', EmployeeController::class);
        Route::post('company/import', 'CompanyController@import')->name('company.import');
        Route::get('company/{id}/print', 'CompanyController@print')->name('company.print');
        Route::post('employee/import', 'EmployeeController@import')->name('employee.import');
    });
});

Modules/Transisi/Entities/Employee.php
<?php

namespace Modules\Transisi\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Employee extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    
    public function company(){
        return $this->belongsTo(Company::class);
    }
}

Modules/Transisi/Http/Controllers/API/EmployeeController.php
<?php

namespace Modules\Transisi\Http\Controllers\API;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use App\Http\Controllers\API\BaseController;
use Exception;
use Modules\Transisi\Entities\Employee;
use Modules\Transisi\Http\Requests\EmployeeStoreRequest;
use Modules\Transisi\Http\Requests\EmployeeUpdateRequest;
use Modules\Transisi\Repositories\EmployeeRepository;

class EmployeeController extends BaseController
{
    function __construct(EmployeeRepository $employeeRepository)
    {
        $this->employeeRepository = $employeeRepository;
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $employee = $this->employeeRepository->all();
        return $this->responseOk($employee);
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(EmployeeStoreRequest $request)
    {
        $validated = $request->validated();
        try {
            return $this->responseOk($this->employeeRepository->store($validated));          
        } catch (Exception $e) {
            throw new $this->responseError('Update gagal!', 422, $e->getMessage());
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $employee = $this->employeeRepository->find($id);
        return $this->responseOk($employee);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(EmployeeUpdateRequest $request, $id)
    {
        $validated = $request->validated();
        try {
            if ($this->employeeRepository->find($id)!=null) {
                return $this->responseOk($this->employeeRepository->update($validated, $id));
            } else {
                throw new Exception("Update on null", 1);
            }          
        } catch (Exception $e) {
            return $this->responseError('Update gagal!', 422, $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        try {
            if ($this->employeeRepository->find($id)!=null) {
                return $this->responseOk($this->employeeRepository->destroy($id));          
            } else {
                throw new Exception("Delete on null", 1);
            }
        } catch (Exception $e) {
            return $this->responseError('Delete gagal!', 422, $e->getMessage());
        }
    }
}

Modules/Transisi/Http/Controllers/EmployeeController.php
<?php

namespace Modules\Transisi\Http\Controllers;

use Exception;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Rap2hpoutre\FastExcel\FastExcel;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\LazyCollection;
use Modules\Transisi\Entities\Employee;
use Modules\Transisi\Http\Requests\EmployeeStoreRequest;
use Modules\Transisi\Http\Requests\EmployeeUpdateRequest;
use Modules\Transisi\Repositories\EmployeeRepository;

class EmployeeController extends Controller
{
    function __construct(EmployeeRepository $employeeRepository)
    {
        $this->employeeRepository = $employeeRepository;
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $employees = $this->employeeRepository->paginate(5);
        if(request()->ajax()){
            return view('transisi::snippets.employee.pagination', compact('employees'))->render();
        }
        return view('transisi::employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('transisi::employee.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(EmployeeStoreRequest $request)
    {
        //
        $validated = $request->validated();
        try {
            $this->employeeRepository->store($validated);
            $msg = 'Data berhasil ditambahkan!';
        } catch (Exception $e) {
            $msg = 'Data gagal ditambahkan!';
        }
        return redirect('transisi/employee')->with('msg', $msg);
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $employee = $this->employeeRepository->find($id);
        return view('transisi::employee.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        return view('transisi::employee.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(EmployeeUpdateRequest $request, $id)
    {
        //
        $validated = $request->validated();
        try {
            $this->employeeRepository->update($validated, $id);
            $msg = 'Data berhasil diubah!';
        } catch (Exception $e) {
            dd($e);
            $msg = 'Data gagal diubah!';
        }
        return redirect('transisi/employee')->with('msg', $msg);
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
        try {
            $this->employeeRepository->destroy($id);
            $msg = 'Data berhasil dihapus!';
        } catch (Exception $e) {
            $msg = 'Data gagal dihapus!';
        }
        return redirect('transisi/employee')->with('msg', $msg);
    }

    /**
     * Return excel report of all company records
     */
    public function export()
    {
        return (new FastExcel($this->employeeRepository->export()))->download('data-employee('.date('d-m-Y').').xlsx');
    }

    /**
     * 
     */
    public function import(Request $request)
    {
        $pathFile = $request->csv->storeAs('public', 'importEmployee.csv');
        $csv = 'storage/app/'.$pathFile;
        $import=LazyCollection::make(function(){
                    $path = storage_path('app/public/importEmployee.csv');
                    $handle = fopen($path, 'r');
                    while($line = fgetcsv($handle)){
                        yield $line;
                    }
                })
                ->chunk(500)
                ->each(function($lines){
                    $list = [];
                    foreach ($lines as $line) {
                        if (isset($line)){
                            $line = explode(';',$line[0]);
                            // dd($line);
                            $list[]=[
                                'name'=>$line[1],
                                'email'=>$line[2],
                                'company_id'=>$line[3]
                            ];
                        }
                    }
                    try {
                        $this->employeeRepository->import($list);
                        $this->msg = 'Data berhasil ditambahkan!';
                    } catch (Exception $e) {
                        $this->msg = 'Data gagal ditambahkan!';
                    }
                });
        Storage::delete('public/importEmployee.csv');
        return redirect('transisi/employee')->with('msg', $this->msg);
    }
    
}

Modules/Transisi/Resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="d-flex flex-row-reverse mb-3">
              <form action="{{ route('employee.import') }}" method="POST" enctype="multipart/form-data" >
                  @csrf
                  <input type="file" name="csv" accept=".csv" required>
                  <button class="btn btn-primary">Import</button>
              </form>
          </div>
            <div class="card">
                <div class="card-header">Tambah Karyawan</div>
                <div class="card-body">
                    <form action="{{ route('employee.store') }}" method="POST">
                      @csrf
                      <div class="mb-3">
                        <select name="company_id" class="form-select" aria-label="Default select example" id="inputCompany">
                          <option selected disabled>Perusahaan</option>
                        </select>
                        @error('company_id')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="inputName" class="form-label">Nama Karyawan</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" placeholder="Nama" id="inputName" name="name" required value="{{ old('name') }}">
                        @error('name')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Alamat Email</label>
                        <input type="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" id="exampleInputEmail1" name="email" required value="{{ old('email') }}">
                        @error('email')
                          <div class="text-danger">
                              {{ $message }}
                          </div>         
                        @enderror
                      </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  $(document).ready(function () {
    $.ajax({
      type: "GET",
      url: "/transisi/company",
      dataType: "json",
      success: function (response) {
          $.each(response.companies, function (index, value) { 
            $('#inputCompany').append(`<option value="`+value.id+`">`+value.name+`</option>`);
          });
      }
    });
  });
</script>
@endsection

Modules/Transisi/Resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Karyawan</div>

                <div class="card-body">
                    <form action="{{ route('employee.update', $employee->id) }}" method="POST">
                      @csrf
                      @method('PUT')
                      <input type="hidden" name="employee_company" value="{{ $employee->company->id }}">
                      <div class="mb-3">
                        <select name="company_id" class="form-select" aria-label="Default select example" id="inputCompany">
                          <option selected disabled>Perusahaan</option>
                        </select>
                        @error('company_id')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <select name="status" class="form-select" aria-label="Default select example" id="inputStatus" required>
                          <option selected disabled>Status</option>
                          @foreach (Status::labels() as $key => $value)
                              <option {{ ($key===$employee->status)?'selected':'' }} value="{{ $key }}">{{ $value }}</option>
                          @endforeach
                        </select>
                        @error('status')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="inputName" class="form-label">Nama Karyawan</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" placeholder="Nama" id="inputName" name="name" required value="{{ $employee->name }}">
                        @error('name')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Alamat Email</label>
                        <input type="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" id="exampleInputEmail1" name="email" required value="{{ $employee->email }}">
                        @error('email')
                          <div class="text-danger">
                              {{ $message }}
                          </div>         
                        @enderror
                      </div>
                      <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  $(document).ready(function () {
    let company_id = $("input[name='employee_company']").val();
    $.ajax({
      type: "GET",
      url: "/transisi/company",
      dataType: "json",
      success: function (response) {
          $.each(response.companies, function (index, value) { 
            let selected = (value.id==company_id) ? 'selected' : '';
            $('#inputCompany').append(`<option value="`+value.id+`" `+selected+`>`+value.name+`</option>`);
          });
      }
    });
  });
</script>
@endsection

Modules/Transisi/Resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('msg'))
                    <div class="alert {{ strpos(session('msg'),'gagal') ? 'alert-danger':'alert-success' }}">{{ session('msg') }}</div>
            @endif
            <div class="d-flex flex-row-reverse mb-3">
                <a href="{{ route('employee.create') }}" class="btn btn-primary">Tambah</a>
                <a href="{{ route('employee.export') }}" class="btn btn-outline-primary mx-2">Export</a>
            </div>
            <div class="card">
                <div class="card-header">{{ __('Employee') }}</div>
                <div class="card-body">
                    @include('transisi::snippets.employee.pagination')
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(document).on('click', '.page-link', function (e) {
            e.preventDefault();
            let page = $(this).attr('href').split('page=')[1];
            fetch(page);
        });

        function fetch(page){
            $.ajax({
                type: "GET",
                url: "/transisi/employee?page="+page,
                dataType: "json",
                success: function (response) {
                },
                error:function(xhr){
                    if(xhr.status==200){
                        $('.card-body').html(xhr.responseText);
                    }
                }
            });
        }
    });
</script>
@endsection

Modules/Transisi/Resources/views/employee/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ $employee->name }}</div>
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center">
                        <h5>{{ $employee->name }}</h5>
                        <small class="d-flex">
                            <p class="mx-2">{{ $employee->email }}</p>
                            <p class="mx-2">Bekerja di {{ $employee->company->name }}</p>
                        </small>
                        <small class="d-flex justify-content-center">
                                <a href="{{ route('employee.edit', $employee->id) }}" class="btn btn-success mx-1">Edit</a>
                                <form action="{{ route('employee.destroy', $employee->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger mx-1">Hapus</button>
                                </form>
                              </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection