Modules/Transisi/Routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('transisi')->group(function() {
        Route::get('company/export', 'CompanyController@export')->name('company.export');
        Route::get('employee/export', 'EmployeeController@export')->name('employee.export');
        Route::resource('company', CompanyController::class);
        Route::resource('employee', EmployeeController::class);
        Route::post('company/import', 'CompanyController@import')->name('company.import');
        Route::get('company/{id}/print', 'CompanyController@print')->name('company.print');
        Route::post('employee/import', 'EmployeeController@import')->name('employee.import');
    });
});

Modules/Transisi/Entities/Company.php
<?php

namespace Modules\Transisi\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Company extends Model
{
    use HasFactory;

    protected $fillable = [];

    public function employees(){
        return $this->hasMany(Employee::class);
    }
}

Modules/Transisi/Http/Controllers/API/CompanyController.php
<?php

namespace Modules\Transisi\Http\Controllers\API;

use App\Http\Controllers\API\BaseController;
use Exception;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Transisi\Entities\Company;
use Modules\Transisi\Http\Requests\CompanyStoreRequest;
use Modules\Transisi\Http\Requests\CompanyUpdateRequest;
use Modules\Transisi\Repositories\CompanyRepository;

class CompanyController extends BaseController
{
    function __construct(CompanyRepository $companyRepository)
    {
        $this->companyRepository = $companyRepository;
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $company = $this->companyRepository->all();
        return $this->responseOk($company);
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(CompanyStoreRequest $request)
    {
        $validated = $request->validated();
        try {
            return $this->responseOk($this->companyRepository->store($validated));          
        } catch (Exception $e) {
            return $this->responseError('Insert gagal!', 422, $e->getMessage());
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $company = $this->companyRepository->find($id)->load('employees');
        return $this->responseOk($company);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(CompanyUpdateRequest $request, $id)
    {
        $validated = $request->validated();
        try {
            return $this->responseOk($this->companyRepository->update($validated, $id));          
        } catch (Exception $e) {
            return $this->responseError('Update gagal!', 422, $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
        try {
            return $this->responseOk($this->companyRepository->destroy($id));          
        } catch (Exception $e) {
            return $this->responseError('Delete gagal!', 422, $e->getMessage());
        }
    }
}

Modules/Transisi/Http/Controllers/CompanyController.php
<?php

namespace Modules\Transisi\Http\Controllers;

use Exception;
use PDF;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\LazyCollection;
use Modules\Transisi\Http\Requests\CompanyStoreRequest;
use Modules\Transisi\Http\Requests\CompanyUpdateRequest;
use Modules\Transisi\Repositories\CompanyRepository;
use Rap2hpoutre\FastExcel\FastExcel;

class CompanyController extends Controller
{
    function __construct(CompanyRepository $companyRepository)
    {
        $this->companyRepository = $companyRepository;
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            if($request->paginate=='true'){
                return view('transisi::snippets.company.pagination', ['companies'=>$this->companyRepository->paginate(5)])->render();
            }
            return response()->json(['msg'=>'Success', 'companies'=>$this->companyRepository->all()]);
        }
        return view('transisi::company.index', ['companies'=>$this->companyRepository->paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('transisi::company.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(CompanyStoreRequest $request)
    {
        //
        $validated = $request->validated();
        // Menyimpan gambar
        $fileName = date("Ymd").time().$request->logo->getClientOriginalName();
        $pathFile = $request->logo->storeAs('company', $fileName);
        $logo = 'storage/app/'.$pathFile;
        $validated['logo'] = $logo;
        // Menyimpan data kedalam database
        try {
            $this->companyRepository->store($validated);
            $msg = 'Data berhasil ditambahkan!';
        } catch (Exception $e) {
            $msg = 'Data gagal ditambahkan!';
        }
        return redirect('transisi/company')->with('msg', $msg);
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $company = $this->companyRepository->find($id);
        $employees = $company->employees()->paginate(5);
        if(request()->ajax()){
            return view('transisi::snippets.company.employeepagination', ['company'=>$company, 'employees'=>$employees])->render();
        }
        return view('transisi::company.show', ['company'=>$company, 'employees'=>$employees]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $company = $this->companyRepository->find($id);
        return view('transisi::company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(CompanyUpdateRequest $request, $id)
    {       
        $company = $this->companyRepository->find($id) ;
        $validated = $request->validated();
        // Menyimpan gambar
        if(isset($request->logo)){
            $fileName = date("Ymd").time().$request->logo->getClientOriginalName();
            $pathFile = $request->logo->storeAs('company', $fileName);
            $logo = 'storage/app/'.$pathFile;
            $validated['logo'] = $logo;
            // Delete old image when user update the image
            Storage::delete(str_replace('storage/app/', '', $company->logo));
        } else{
            $validated['logo'] = $company->logo;
        }
        // Update data
        try {
            $this->companyRepository->update($validated, $id);
            $msg = 'Data berhasil diubah!';
        } catch (Exception $e) {
            $msg = 'Data gagal diubah!';
        }
        return redirect('transisi/company')->with('msg', $msg);

    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
        $company = $this->companyRepository->find($id);
        // Delete logo saved on storage
        Storage::delete(str_replace('storage/app/', '', $company->logo));
        try {
            $this->companyRepository->destroy($id);
            $msg = 'Data berhasil dihapus!';
        } catch (Exception $e) {
            $msg = 'Data gagal dihapus!';
        }
        return redirect('transisi/company')->with('msg', $msg);
    }

    /**
     * Return pdf report of specific company
     * @param int $id
     */
    public function print($id)
    {
        $data = $this->companyRepository->print($id);
        $pdf = PDF::loadView('transisi::company.pdf', compact('data'));
        return $pdf->download(date('d-m-Y').'_'.str_replace(' ', '-', $data['company']->name).'.pdf');
    }

    /**
     * Return excel report of all company records
     */
    public function export()
    {
        return (new FastExcel($this->companyRepository->export()))->download('data-company('.date('d-m-Y').').xlsx');
    }

    /**
     * 
     */
    public function import(Request $request)
    {
        $pathFile = $request->csv->storeAs('public', 'importCompany.csv');
        $csv = 'storage/app/'.$pathFile;
        $import=LazyCollection::make(function(){
                    $path = storage_path('app/public/importCompany.csv');
                    $handle = fopen($path, 'r');
                    while($line = fgetcsv($handle)){
                        yield $line;
                    }
                })
                ->chunk(500)
                ->each(function($lines){
                    $list = [];
                    foreach ($lines as $line) {
                        if (isset($line)){
                            $line = explode(';',$line[0]);
                            $list[]=[
                                'name'=>$line[1],
                                'email'=>$line[2],
                                'website'=>$line[3],
                                'logo'=>$line[4]
                            ];
                        }
                    }
                    try {
                        $this->companyRepository->import($list);
                        $this->msg = 'Data berhasil ditambahkan!';
                    } catch (Exception $e) {
                        $this->msg = 'Data gagal ditambahkan!';
                    }
                });
        Storage::delete('public/importCompany.csv');
        return redirect('transisi/company')->with('msg', $this->msg);
    }
}

Modules/Transisi/Resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="d-flex flex-row-reverse mb-3">
                <form action="{{ route('company.import') }}" method="POST" enctype="multipart/form-data" >
                    @csrf
                    <input type="file" name="csv" accept=".csv" required>
                    <button class="btn btn-primary">Import</button>
                </form>
                
            </div>
            <div class="card">
                <div class="card-header">{{ __('Tambah Company') }}</div>

                <div class="card-body">
                    <form action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                      <div class="mb-3">
                        <label for="inputName" class="form-label">Nama Company</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" placeholder="Nama Perusahaan" id="inputName" name="name" required value="{{ old('name') }}">
                        @error('name')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Alamat Email</label>
                        <input type="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email Perusahaan" id="exampleInputEmail1" name="email" required value="{{ old('email') }}">
                        @error('email')
                          <div class="text-danger">
                              {{ $message }}
                          </div>         
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="inputWebsite" class="form-label">Website</label>
                        <input type="text" class="form-control @error('website') is-invalid @enderror" placeholder="Website Perusahaan" id="inputWebsite" name="website" required value="{{ old('website') }}">
                        @error('website')
                          <div class="text-danger">
                              {{ $message }}
                          </div>                  
                        @enderror
                      </div>
                      <div class="mb-3">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-column w-100 my-auto">
                                <label for="inputLogo" class="form-label">Logo</label>
                                <input type="file" class="form-" id="inputLogo" name="logo" accept="image/png" required>
                                <label class="text-muted">Ukuran maksimal 2 MB. Minimal 100x100px</label>
                                @error('logo')
                                    <div class="text-danger">
                                        {{ $message }}
                                    </div>         
                                @enderror    
                            </div>    
                            <div class="img-upload" style="max-width: 150px; max-height: 150px;">
                                <img src="" class="w-100 h-100" id="img-box">    
                            </div>
                        </div>
                      </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#inputLogo').change(function(input){
            let file = input.target.files;
            let reader = new FileReader();
            reader.onload = function(e){
                $('#img-box').attr('src',e.target.result);
            }
            reader.readAsDataURL(file[0]);
        });
    });
</script>
@endsection

Modules/Transisi/Resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit {{ $company->name }}</div>

                <div class="card-body">
                    <form action="{{ route('company.update', $company->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                      <div class="mb-3">
                        <label for="inputName" class="form-label">Nama Company</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" placeholder="Nama Perusahaan" id="inputName" name="name" required value="{{ $company->name }}">
                        @error('name')
                          <div class="text-danger">
                              {{ $message }}
                          </div>          
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Alamat Email</label>
                        <input type="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email Perusahaan" id="exampleInputEmail1" name="email" required value="{{ $company->email }}">
                        @error('email')
                          <div class="text-danger">
                              {{ $message }}
                          </div>         
                        @enderror
                      </div>
                      <div class="mb-3">
                        <label for="inputWebsite" class="form-label">Website</label>
                        <input type="text" class="form-control @error('website') is-invalid @enderror" placeholder="Website Perusahaan" id="inputWebsite" name="website" required value="{{ $company->website }}">
                        @error('website')
                          <div class="text-danger">
                              {{ $message }}
                          </div>                  
                        @enderror
                      </div>
                      <div class="mb-3">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-column w-100 my-auto">
                                <label for="inputLogo" class="form-label">Logo</label>
                                <input type="file" class="form-" id="inputLogo" name="logo" accept="image/png" value="{{ $company->logo }}">
                                <label class="text-muted">Ukuran maksimal 2 MB. Minimal 100x100px</label>
                                @error('logo')
                                    <div class="text-danger">
                                        {{ $message }}
                                    </div>         
                                @enderror    
                            </div>    
                            <div class="img-upload" style="max-width: 150px; max-height: 150px;">
                                <img src="/{{ $company->logo }}" class="w-100 h-100" id="img-box">    
                            </div>
                        </div>
                      </div>
                      <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#inputLogo').change(function(input){
            let file = input.target.files;
            let reader = new FileReader();
            reader.onload = function(e){
                $('#img-box').attr('src',e.target.result);
            }
            reader.readAsDataURL(file[0]);
        });
    });
</script>
@endsection

Modules/Transisi/Resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('msg'))
                <div class="alert {{ strpos(session('msg'),'gagal') ? 'alert-danger':'alert-success' }}">{{ session('msg') }}</div>
            @endif
            <div class="d-flex flex-row-reverse mb-3">
                <a href="{{ route('company.create') }}" class="btn btn-primary">Tambah</a>
                <a href="{{ route('company.export') }}" class="btn btn-outline-primary mx-2">Export</a>
            </div>
            <div class="card">
                <div class="card-header">{{ __('Company') }}</div>
                <div class="card-body">
                    @include('transisi::snippets.company.pagination')
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(document).on('click', '.page-link', function (e) {
            e.preventDefault();
            let page = $(this).attr('href').split('page=')[1];
            fetch(page);
        });

        function fetch(page){
            $.ajax({
                type: "GET",
                url: "/transisi/company?page="+page,
                data: {paginate:'true'},
                dataType: "json",
                success: function (response) {
                },
                error:function(xhr){
                    if(xhr.status==200){
                        $('.card-body').html(xhr.responseText);
                    }
                }
            });
        }
    });
</script>
@endsection

Modules/Transisi/Resources/views/company/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
		<h1>Laporan Data Karyawan {{ $data['company']->name }}</h1>
		<table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Email</th>
            </tr>
            @foreach ($data['employees'] as $item)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->email }}</td>
            </tr>
            @endforeach
        </table>
	</div>
</body>
</html>

Modules/Transisi/Resources/views/company/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="d-flex flex-row-reverse my-3">
                <a href="{{ route('company.print', $company->id) }}" class="btn btn-success">Export PDF</a>
            </div>
            <div class="card">
                <div class="card-header">Edit {{ $company->name }}</div>
                <input type="hidden" value="{{ $company->id }}" id="company_id">
                <div class="card-body">
                    @include('transisi::snippets.company.employeepagination')
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        let company_id = $('#company_id').val();
        $(document).on('click', '.page-link', function (e) {
            e.preventDefault();
            let page = $(this).attr('href').split('page=')[1];
            fetch(page);
        });

        function fetch(page){
            $.ajax({
                type: "GET",
                url: "/transisi/company/"+company_id+"?page="+page,
                dataType: "json",
                success: function (response) {
                },
                error:function(xhr){
                    if(xhr.status==200){
                        $('.card-body').html(xhr.responseText);
                    }
                }
            });
        }
    });
</script>
@endsection