Modules/Transisi/Routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    Route::prefix('transisi')->group(function() {
        Route::get('company/export', 'CompanyController@export')->name('company.export');
        Route::get('employee/export', 'EmployeeController@export')->name('employee.export');
        Route::resource('company', CompanyController::class);
        Route::resource('employee', EmployeeController::class);
        Route::post('company/import', 'CompanyController@import')->name('company.import');
        Route::get('company/{id}/print', 'CompanyController@print')->name('company.print');
        Route::post('employee/import', 'EmployeeController@import')->name('employee.import');
    });
});

Modules/Transisi/Entities/Company.php
<?php

namespace Modules\Transisi\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Company extends Model
{
    use HasFactory;

    protected $fillable = [];

    public function employees(){
        return $this->hasMany(Employee::class);
    }
}

Modules/Transisi/Http/Controllers/API/CompanyController.php
<?php

namespace Modules\Transisi\Http\Controllers\API;

use App\Http\Controllers\API\BaseController;
use Exception;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Transisi\Entities\Company;
use Modules\Transisi\Http\Requests\CompanyStoreRequest;
use Modules\Transisi\Http\Requests\CompanyUpdateRequest;
use Modules\Transisi\Repositories\CompanyRepository;

class CompanyController extends BaseController
{
    function __construct(CompanyRepository $companyRepository)
    {
        $this->companyRepository = $companyRepository;
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $company = $this->companyRepository->all();
        return $this->responseOk($company);
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(CompanyStoreRequest $request)
    {
        $validated = $request->validated();
        try {
            return $this->responseOk($this->companyRepository->store($validated));          
        } catch (Exception $e) {
            return $this->responseError('Insert gagal!', 422, $e->getMessage());
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $company = $this->companyRepository->find($id)->load('employees');
        return $this->responseOk($company);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(CompanyUpdateRequest $request, $id)
    {
        $validated = $request->validated();
        try {
            return $this->responseOk($this->companyRepository->update($validated, $id));          
        } catch (Exception $e) {
            return $this->responseError('Update gagal!', 422, $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
        try {
            return $this->responseOk($this->companyRepository->destroy($id));          
        } catch (Exception $e) {
            return $this->responseError('Delete gagal!', 422, $e->getMessage());
        }
    }
}

Modules/Transisi/Http/Controllers/CompanyController.php
<?php

namespace Modules\Transisi\Http\Controllers;

use Exception;
use PDF;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\LazyCollection;
use Modules\Transisi\Http\Requests\CompanyStoreRequest;
use Modules\Transisi\Http\Requests\CompanyUpdateRequest;
use Modules\Transisi\Repositories\CompanyRepository;
use Rap2hpoutre\FastExcel\FastExcel;

class CompanyController extends Controller
{
    function __construct(CompanyRepository $companyRepository)
    {
        $this->companyRepository = $companyRepository;
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            if($request->paginate=='true'){
                return view('transisi::snippets.company.pagination', ['companies'=>$this->companyRepository->paginate(5)])->render();
            }
            return response()->json(['msg'=>'Success', 'companies'=>$this->companyRepository->all()]);
        }
        return view('transisi::company.index', ['companies'=>$this->companyRepository->paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('transisi::company.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(CompanyStoreRequest $request)
    {
        //
        $validated = $request->validated();
        // Menyimpan gambar
        $fileName = date("Ymd").time().$request->logo->getClientOriginalName();
        $pathFile = $request->logo->storeAs('company', $fileName);
        $logo = 'storage/app/'.$pathFile;
        $validated['logo'] = $logo;
        // Menyimpan data kedalam database
        try {
            $this->companyRepository->store($validated);
            $msg = 'Data berhasil ditambahkan!';
        } catch (Exception $e) {
            $msg = 'Data gagal ditambahkan!';
        }
        return redirect('transisi/company')->with('msg', $msg);
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        $company = $this->companyRepository->find($id);
        $employees = $company->employees()->paginate(5);
        if(request()->ajax()){
            return view('transisi::snippets.company.employeepagination', ['company'=>$company, 'employees'=>$employees])->render();
        }
        return view('transisi::company.show', ['company'=>$company, 'employees'=>$employees]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $company = $this->companyRepository->find($id);
        return view('transisi::company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(CompanyUpdateRequest $request, $id)
    {       
        $company = $this->companyRepository->find($id) ;
        $validated = $request->validated();
        // Menyimpan gambar
        if(isset($request->logo)){
            $fileName = date("Ymd").time().$request->logo->getClientOriginalName();
            $pathFile = $request->logo->storeAs('company', $fileName);
            $logo = 'storage/app/'.$pathFile;
            $validated['logo'] = $logo;
            // Delete old image when user update the image
            Storage::delete(str_replace('storage/app/', '', $company->logo));
        } else{
            $validated['logo'] = $company->logo;
        }
        // Update data
        try {
            $this->companyRepository->update($validated, $id);
            $msg = 'Data berhasil diubah!';
        } catch (Exception $e) {
            $msg = 'Data gagal diubah!';
        }
        return redirect('transisi/company')->with('msg', $msg);

    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
        $company = $this->companyRepository->find($id);
        // Delete logo saved on storage
        Storage::delete(str_replace('storage/app/', '', $company->logo));
        try {
            $this->companyRepository->destroy($id);
            $msg = 'Data berhasil dihapus!';
        } catch (Exception $e) {
            $msg = 'Data gagal dihapus!';
        }
        return redirect('transisi/company')->with('msg', $msg);
    }

    /**
     * Return pdf report of specific company
     * @param int $id
     */
    public function print($id)
    {
        $data = $this->companyRepository->print($id);
        $pdf = PDF::loadView('transisi::company.pdf', compact('data'));
        return $pdf->download(date('d-m-Y').'_'.str_replace(' ', '-', $data['company']->name).'.pdf');
    }

    /**
     * Return excel report of all company records
     */
    public function export()
    {
        return (new FastExcel($this->companyRepository->export()))->download('data-company('.date('d-m-Y').').xlsx');
    }

    /**
     * 
     */
    public function import(Request $request)
    {
        $pathFile = $request->csv->storeAs('public', 'importCompany.csv');
        $csv = 'storage/app/'.$pathFile;
        $import=LazyCollection::make(function(){
                    $path = storage_path('app/public/importCompany.csv');
                    $handle = fopen($path, 'r');
                    while($line = fgetcsv($handle)){
                        yield $line;
                    }
                })
                ->chunk(500)
                ->each(function($lines){
                    $list = [];
                    foreach ($lines as $line) {
                        if (isset($line)){
                            $line = explode(';',$line[0]);
                            $list[]=[
                                'name'=>$line[1],
                                'email'=>$line[2],
                                'website'=>$line[3],
                                'logo'=>$line[4]
                            ];
                        }
                    }
                    try {
                        $this->companyRepository->import($list);
                        $this->msg = 'Data berhasil ditambahkan!';
                    } catch (Exception $e) {
                        $this->msg = 'Data gagal ditambahkan!';
                    }
                });
        Storage::delete('public/importCompany.csv');
        return redirect('transisi/company')->with('msg', $this->msg);
    }
}

Modules/Transisi/Resources/views/snippets/company/employeepagination.blade.php
<div class="d-flex flex-column align-items-center">
    <div class="logo" style="max-width: 250px; max-height: 250px;">
        <img class="img-fluid" src="{{ url($company->logo) }}"></img>
    </div>
    <h5>{{ $company->name }}</h5>
    <small class="d-flex">
        <p class="mx-2">{{ $company->email }}</p>
        <a target="blank" href="http://www.{{ $company->website }}" class="mx-2 tex-decoration-none">{{ $company->website }}</a>
    </small>
    <div class="list-group mb-2">
        @foreach($employees as $employee)
        <div class="list-group-item list-group-item-action mb-2">
              <div class="d-flex w-100 justify-content-between">
                <a href="{{ route('employee.show', $employee->id) }}" class="text-decoration-none text-dark"><h5 class="mb-1">{{ $employee->name }}</h5></a>
                <small class="d-flex">
                  <a href="{{ route('employee.edit', $employee->id) }}" class="btn btn-success mx-1">Edit</a>
                  <form action="{{ route('employee.destroy', $employee->id) }}" method="POST">
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger mx-1">Hapus</button>
                  </form>
                </small>
              </div>
              <p class="mb-1">{{ $employee->email }}</p>    
        </div>
        @endforeach
    </div>
</div>
<div class="d-flex justify-content-end">
    {{ $employees->links() }}    
</div>

Modules/Transisi/Resources/views/snippets/company/pagination.blade.php
<div class="list-group mb-2">
    @foreach($companies as $company)
        <div class="list-group-item list-group-item-action mb-2">
            <div class="d-flex">
                <div class="logo" style="width: 100px;height: 100px">
                    <img class="w-100 h-100" src="{{ url($company->logo) }}"></img>
                </div>
                <div class="description w-100 mx-3">
                    <div class="d-flex w-100 justify-content-between">
                    <a href="{{ route('company.show', $company->id) }}" class="text-decoration-none text-dark"><h5 class="mb-1">{{ $company->name }}</h5></a>
                    <small class="d-flex">
                        <a href="{{ route('company.edit', $company->id) }}" class="btn btn-success mx-1">Edit</a>
                        <form action="{{ route('company.destroy', $company->id)  }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger mx-1">Hapus</button>
                        </form>
                    </small>
                    </div>
                    <h5 class="mb-1"></h5>
                    <p class="mb-1">{{ $company->email }}</p>
                    <small class="text-muted">{{ $company->website }}</small>        
                </div>
            </div>
        </div>
    @endforeach
</div>
<div class="d-flex justify-content-end">
    {{ $companies->links() }}    
</div>